### PR TITLE
Properly handle LOB types with rowsAsArray set

### LINKED ISSUE #78: rowsAsArray: true leads to errors when one of the resultset columns is NCLOB
node version: 6.9.5
hdb version 0.12.0

When using `connection.exec` with the rowsAsArray: true option and having a column of type NCLOB (---> Buffer) in the resultSet the query fails with the following error:

Error message: 
```text
    Uncaught TypeError: Cannot read property 'read' of undefined
      at next (node_modules/@sap/hdbext/node_modules/hdb/lib/protocol/ResultSet.js:447:8)
      at Writable.collectLobRow (node_modules/@sap/hdbext/node_modules/hdb/lib/protocol/ResultSet.js:449:3)
```

I guess this has to do something with the fact that the columns / cell value is represented as Buffer.

### PR DESCRIPTION
**Pull request by alexpenev-s**
Fixes #78

### CODE REVIEW

File: lib/protocol/ResultSet.js [hunk 1]
```diff
@@ -150,6 +150,15 @@ ResultSet.prototype.getLobColumnNames = function getLobColumnNames() {
   return this.metadata.filter(isLob).map(getColumName);
 };
 
+ResultSet.prototype.getLobColumnIndexes = function getLobColumnIndexes() {
+  return this.metadata.reduce(function(p, c, i) {
+    if (isLob(c)) {
+      p.push(i);
+    }
+    return p;
+  }, [])
```
Comment (petar-iv) [inline lib/protocol/ResultSet.js]: Missing `;` here.

File: test/lib.ResultSet.js [hunk 2]
```diff
@@ -338,6 +338,35 @@ describe('Lib', function () {
       });
 
     it(
+      'should fetch all rows with a LOB and rowsAsArray set',
```
Comment (petar-iv) [inline test/lib.ResultSet.js]: Although there are test cases that are _not_ properly formatted, in this file there are still test cases that _are_ properly formatted. Better use proper formatting for your test as well `it('...', function (done) {   .......`.

File: lib/protocol/ResultSet.js (hunk 1 above)
Comment (petar-iv) [inline lib/protocol/ResultSet.js]: Something simpler like:

```js
var indexes = [];
for (var idx in this.metadata) {
  isLob(this.metadata[idx]) && indexes.push(idx);
}
return indexes;
```

should work as well. This would be simpler, because in your case with `reduce` the accumulated value is also an array.

Comment (alexpenev-s) [inline lib/protocol/ResultSet.js]: Ok I will change it to a for loop.

File: test/lib.ResultSet.js (hunk 2 above)
Comment (alexpenev-s) [inline test/lib.ResultSet.js]: I think the formatting is such so that the max line character length in approximately 80.
If you look at the ones that are properly formatted you will notice that they are below 80; however the longer ones that exceed 80 are split into multiple lines.
